name: model_builder
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - xlrd
  - openpyxl
  - pandas
  - pip
  - pip:
    options: --force-reinstall
      - https://github.com/Bureau-du-Forestier-en-chef/FMT/releases/download/v1.0.0/FMT-1.0.0-cp310-cp310-win_amd64.whl